services:
  backend:
    build: ./backend-fastapi
    env_file:
      - .env
    # environment:
      # - SUPABASE_PASSWORD
      # - SUPABASE_KEY
    container_name: insurance-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    develop:
      watch:
        - action: sync
          path: backend-fastapi/app
          target: code/app
          ignore: backend-fastapi/.venv

    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
